name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip
        chmod +x ngrok

    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create user and set password
      run: |
        sudo useradd -m runneradmin
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd
        echo "runneradmin ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/runneradmin

    - name: Install and start SSH service
      run: |
        sudo apt update
        sudo apt install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        sudo systemctl status ssh

    - name: Expose SSH via ngrok
      run: ./ngrok tcp 22
