name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip
        chmod +x ngrok

    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create user and set password
      run: |
        sudo useradd -m -s /bin/bash runneradmin
        echo 'runneradmin:P@ssw0rd!' | sudo chpasswd
        echo 'runneradmin ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/runneradmin

    - name: Configure and start SSH
      run: |
        sudo apt update
        sudo apt install -y openssh-server
        sudo sed -i 's/^#\?PasswordAuthentication .*/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo sed -i 's/^#\?PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
        echo "AllowUsers runneradmin" | sudo tee -a /etc/ssh/sshd_config
        sudo systemctl restart ssh

    - name: Expose SSH via ngrok
      run: ./ngrok tcp 22
