name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update and install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl sudo

    - name: Install ngrok via APT
      run: |
        curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
        | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
        | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update
        sudo apt install -y ngrok

    - name: Create user 'ethan'
      run: |
        sudo useradd -m ethan
        echo "ethan:P@ssw0rd!" | sudo chpasswd
        sudo usermod -aG sudo ethan

    - name: Authenticate ngrok
      run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok TCP tunnel for TigerVNC (port 5900)
      run: ngrok tcp 5900
