name: SSH over ngrok

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Install and start SSH server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        sudo ufw allow 22/tcp
        sudo ufw reload

    - name: Set password for user runneradmin
      run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok TCP tunnel for SSH
      run: ./ngrok tcp 22
